### ISSUE TITLE
Error running on latest macOS runner

### ISSUE THREAD

**Issue by donfuldauereko** [actions/delete-package-versions#196]
The following occurs when running from macOS 14, which is now used for `macos-default`.

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:24700:26)
    at osName (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:26806:18)
    at getUserAgent (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:16583:53)
    at parseOptions (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:15874:57)
    at new Octokit (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:15754:31)
    at Object.5438 (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:[21](https://github.com/EkoDevices/INTERNAL-Eko-KMM-Shared/actions/runs/8943239588/job/24567512809#step:13:22)03:28)
    at __nccwpck_require__ (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:43902:43)
    at /Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:43926:18
    at /Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:43964:3
    at Object.<anonymous> (/Users/runner/work/_actions/actions/delete-package-versions/v4/dist/index.js:43967:12)
```

**Comment by ifeomaro** [comment]
This is still an issue on the latest macOS runner. Is anyone able to resolve this and/or review/merge the linked the PR?
